### ISSUE TITLE
Phonegap avatar is broken (at least on Chrome)

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Marketing-Cloud/adobe-marketing-cloud.github.io#5]
On http://adobe-marketing-cloud.github.io/, the phonegap organization's avatar shows for me as a broken image.

@paolomoz can you take a look at this?

**Comment by justinedelson** [comment]
Also true of the phonegap-build avatar

**Comment by paolomoz** [comment]
fixed thanks @justinedelson for your note
